[firebase_credentials]
type = "service_account"
project_id = "anomaly-detection-2052d"
private_key_id = "379901f05548cb825285175266cb12c235888f5c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDaYFI6tBFAv9CU
eZINngNM+6J21hQUqqc1t89CG/N04YjakvgOcEwoFYO/wDAbaui8UY/3Vo8ctOiV
...
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@anomaly-detection-2052d.iam.gserviceaccount.com"
client_id = "111205714020679036694"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40anomaly-detection-2052d.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

firebase_api_key = "AIzaSyBYfbg6GmkKHO0r_Y4TEMVyvzxlRQ1ZTTY"
influxdb_token = "6gjE97dCC24hgOgWNmRXPqOS0pfc0pMSYeh5psL8e5u2T8jGeV1F17CU-U1z05if0jfTEmPRW9twNPSXN09SRQ=="
