API_URL = "https://mizzony-dos-anomaly-detection.hf.space/predict"
DOS_API_URL = "https://kingxsley-dos-api.hf.space/predict"
DOS_DISCORD_WEBHOOK = "https://discord.com/api/webhooks/1383262825534984243/mMaPgCDV7tgEMsT_-5ABWpnxMJB746kM_hQqFa2F87lRKeBqCx9vyGY6sEyoY4NnZ7d7"
DOS_INFLUXDB_URL = "https://us-east-1-1.aws.cloud2.influxdata.com"
DOS_INFLUXDB_ORG = "Anormally Detection"
DOS_INFLUXDB_BUCKET = "realtime"
DOS_INFLUXDB_TOKEN = "DfmvA8hl5EeOcpR-d6c_ep6dRtSRbEcEM_Zqp8-1746dURtVqMDGni4rRNQbHouhqmdC7t9Kj6Y-AyOjbBg-zg=="
DOS_SQLITE_HOST = "cfolwawehk.g2.sqlite.cloud"
DOS_SQLITE_PORT = 8860
DOS_SQLITE_DB = "dos"
DOS_SQLITE_APIKEY = "77cz3yvotfOw3EgNIM9xPLAWaajazSyxcnCWvvbxFEA"
