# --- DoS Settings (Using Streamlit Secrets with DOS_ prefix) ---
DOS_API_URL = st.secrets.get("DOS_API_URL", "")
DOS_DISCORD_WEBHOOK = st.secrets.get("DOS_DISCORD_WEBHOOK", "")
DOS_INFLUXDB_URL = st.secrets.get("DOS_INFLUXDB_URL", "")
DOS_INFLUXDB_ORG = st.secrets.get("DOS_INFLUXDB_ORG", "")
DOS_INFLUXDB_BUCKET = st.secrets.get("DOS_INFLUXDB_BUCKET", "")
DOS_INFLUXDB_TOKEN = st.secrets.get("DOS_INFLUXDB_TOKEN", "")
DOS_SQLITE_HOST = st.secrets.get("DOS_SQLITE_HOST", "")
DOS_SQLITE_PORT = int(st.secrets.get("DOS_SQLITE_PORT", 8860))
DOS_SQLITE_DB = st.secrets.get("DOS_SQLITE_DB", "")
DOS_SQLITE_APIKEY = st.secrets.get("DOS_SQLITE_APIKEY", "")
