[firebase_credentials]
type = "service_account"
project_id = "anomaly-detection-2052d"
private_key_id = "379901f05548cb825285175266cb12c235888f5c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDaYFI6tBFAv9CU
eZINngNM+6J21hQUqqc1t89CG/N04YjakvgOcEwoFYO/wDAbaui8UY/3Vo8ctOiV
Xl/mGY5+KLwWFH5I8o2+B/2yuXkDg3sG0CdBagOp7NG5TEFOcO4/qWUx9p88Moyp
M56Ts1VHlDq4ZqjeOt6VIKJd0V3EHwZSBk8pupVJlY3fRbVbHROY614Z3L63J0AW
Q629ra8haHa/NUxhtEAs8VBU+5l1XyC8rAbHI6bk2To0hsgTV+GWR9ItnDt5UohR
zs/alDDBRQr1R4ukCUzZWlzInWAbMYAU5calB3vbWb+NY/8hQWtERXyUsR+0For/
FdkOqtalAgMBAAECggEAJ/8AyIou58RJ/Euo3bAdbCXha3EJtABOiEbuYa4TYMqn
AVtuLdzRAf1wyDe3x+nEjytEGjnDE++pcqQand7762zkCApAV/V+0vmNNIUGXkeg
So7oxbEYUzDR96V5B5gk9sl8hJJmN0UN4LaY2nX7zlSejaQV1UAEgN09h7/fM9ph
Nlw/QNt/TpovCGi8PdA2aS/bD4r6bxpjb4v0LvBPQcW3X2MfAc2d50upA2h1nNs3
l0aDOB1R6/1/uSe5I2OrmUrrDD/Ehfc7eDii4YWM4QuPovppNbVQ/VA+wEi9OnWO
zdWZe3ifTP1ON6haKx4a5I+D6UNWAC40wfE8TaOiSQKBgQDsvFO97fFYz15xrf8R
DUiQbVnjQ94FddYHmemSeJx5HrxjigezJc7O6ktitqvit6B/4e1kEg1hHkvpezm1
WNDUIW+E2gxW8m0Kl8uBole+tF5A24IOEpGn8zeIFZ9SpjbOC09M2EeO0wvkJ33t
R0ysC9WRIez1rYe+lh5N6nsheQKBgQDsJYgMZILTPATcCYa9Ey+HPZWZ9zTelllE
AQcZn+FPeUqRU3agWok2WwIZbHrpkDgh7zC0xOPPj50pmFtBS4F1rKB1kWUEu14R
Xhw2xaDtVRHmNEfUcYi75IP3QSl/HNONxFQf0/eEBhmL+ZnpqQZY6Jwvh9UmuY46
sm4M2PnfjQKBgGzbzMYxfCGSeaNcl0WIDi4bmpHey2FHZjvoknc/7vPjJk2/UvsW
D5smMbQau79tIOitQzQY+P4HqHCcsVSqmpxxI467laEFqQ6N7o6V0DNpTU4VoiBG
eaP5OzfgeXrP47Orj7OOYJlUgstPPaC2gJM8feBW8VenjBwfe5/oiuZBAoGBALL/
vAGQyq3th812lyCJA3TjFJwxi2zR0HZAxS4CR9pjGUfRWVExb2K5V30IAp86h6IJ
WgUcXYZ+2OWnrDxxTH9zS+nyPP16PVKy4HYQFezwl/HEXVJGgRvTmsh4J0lIA4Ap
eo7psGvt5713hNheHAaWw5UvxD1nV81cZRjt+3IdAoGAXAY3sXPnnsUTYWukSwNC
GcTtYXW60gPf49dAKC30vRPbSI8fsXdTk/np+2tVHtAQxPYpP+I/oM49nHwZgrF4
ioWA3JCXPRZ9WE+2OKGRAfwUhHowm7xVgG916STzkYlrI54H28Xo9vkKsboBkxKq
m2v2La03nZuaJFYGROWNGr0=
-----END PRIVATE KEY-----
"""
firebase_api_key = "AIzaSyBYfbg6GmkKHO0r_Y4TEMVyvzxlRQ1ZTTY"

influxdb_token = "6gjE97dCC24hgOgWNmRXPqOS0pfc0pMSYeh5psL8e5u2T8jGeV1F17CU-U1z05if0jfTEmPRW9twNPSXN09SRQ=="
